cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/yann/291/Proj1/ntu-dsi-dcn-portland/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/home/yann/291/Proj1/ntu-dsi-dcn-portland/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Build.py", line 193, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 140259278925648: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-fstack-protector-strong\', \'-fno-strict-aliasing\', \'-fno-strict-aliasing\', \'-fstack-protector-strong\', \'-fwrapv\', \'-I/usr/include/python2.7\', \'-I/usr/include/x86_64-linux-gnu/python2.7\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DDL=1\', \'-DXML2=1\', \'-DSQLITE3=1\', \'-DHAVE_IF_TUN_H=1\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYEMBED=1\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'-D_FORTIFY_SOURCE=2\', \'-DNDEBUG\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
